name: "KTU OOP Report generator"
description: "Generate a pdf report from a toml file"
author: "Rokas Puzonas"

inputs:
  config-filename:
    description: "Input toml filename"
  output-filename:
    description: "Output filename"
    default: ""
    optional: true
  dotnet-version:
    description: "Dotnet SDK version"
    optional: true

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Setup Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.x
    - name: Clone report generator
      run: git clone https://github.com/RokasPuzonas/ktu-oop-report-generator -b v2.0.2
      shell: "bash"
    - name: Generate report
      run: |
        cd ktu-oop-report-generator
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        ./main.py "../${{ inputs.config-filename }}" "../${{ inputs.output-filename }}"
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      shell: "bash"
    - name: Cleanup
      run: rm -rf ktu-oop-report-generator
      shell: "bash"
